services:
  postgres:
    image: postgres:16
    container_name: aqua-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aqua_db
    ports:
      - "5432:5432"
    volumes:
      - aqua_postgres_data:/var/lib/postgresql/data

volumes:
  aqua_postgres_data:
